import { useTranslate } from '@Shared/translate.js';
const { setBulk } = useTranslate();

setBulk({
    en: {
        'character.creator.unable.to.save': 'Unable to save character, rejoin server',
        'character.creator.blemishes': 'Blemishes',
        'character.creator.visibility': 'Visibility',
        'character.creator.sun.damage': 'Sun Damage',
        'character.creator.damage': 'Damage',
        'character.creator.freckles': 'Freckles',
        'character.creator.aging': 'Aging',
        'character.creator.lipstick': 'Lipstick',
        'character.creator.color': 'Color',
        'character.creator.blusher': 'Blusher',
        'character.creator.makeup': 'Makeup',
        'character.creator.blemish': 'Blemish',
        'character.creator.face.father': 'Face Father',
        'character.creator.face.mother': 'Face Mother',
        'character.creator.skin.father': 'Skin Father',
        'character.creator.skin.mother': 'Skin Mother',
        'character.creator.skin.mix': 'Skin Mix',
        'character.creator.face.mix': 'Face Mix',
        'character.creator.eyes': 'Eyes',
        'character.creator.body.type': 'Body Type',
        'character.creator.save': 'Save',
        'character.creator.processing': 'Processing...',
        'character.creator.hair': 'Hair',
        'character.creator.hair.color': 'Hair Color',
        'character.creator.hair.highlight': 'Hair Highlight',
        'character.creator.eyebrows': 'Eyebrows',
        'character.creator.eyebrows.color': 'Eyebrows Color',
        'character.creator.facial.hair': 'Facial Hair',
        'character.creator.facial.color': 'Facial Hair Color',
        'character.creator.category': 'Category',
        'character.creator.nose.width': 'Nose Width',
        'character.creator.nose.height': 'Nose Height',
        'character.creator.nose.length': 'Nose Length',
        'character.creator.nose.profile': 'Nose Profile',
        'character.creator.nose.tip': 'Nose Tip',
        'character.creator.nose.broke': 'Nose Broke',
        'character.creator.brow.height': 'Brow Height',
        'character.creator.brow.depth': 'Brow Depth',
        'character.creator.cheek.height': 'Cheek Height',
        'character.creator.cheek.depth': 'Cheek Depth',
        'character.creator.cheek.puffed': 'Cheek Puffed',
        'character.creator.eyes.size': 'Eyes Size',
        'character.creator.lips.size': 'Lips Size',
        'character.creator.jaw.width': 'Jaw Width',
        'character.creator.jaw.rounded': 'Jaw Round',
        'character.creator.chin.height': 'Chin Height',
        'character.creator.chin.depth': 'Chin Depth',
        'character.creator.chin.pointed': 'Chin Pointed',
        'character.creator.chin.dimple': 'Chin Dimple',
        'character.creator.neck.size': 'Neck Size',
    },
    uk: {
        'character.creator.unable.to.save': 'Не вдалося зберегти персонажа, перезапустіть гру',
        'character.creator.blemishes': 'Дефекти шкіри',
        'character.creator.visibility': 'Видимість',
        'character.creator.sun.damage': 'Загар',
        'character.creator.damage': 'Пошкодження',
        'character.creator.freckles': 'Веснянки',
        'character.creator.aging': 'Старіння',
        'character.creator.lipstick': 'Помада',
        'character.creator.color': 'Колір',
        'character.creator.blusher': 'Рум\'яна',
        'character.creator.makeup': 'Макіяж',
        'character.creator.blemish': 'Плями',
        'character.creator.face.father': 'Обличчя батька',
        'character.creator.face.mother': 'Обличчя матері',
        'character.creator.skin.father': 'Шкіра батька',
        'character.creator.skin.mother': 'Шкіра матері',
        'character.creator.skin.mix': 'Змішування шкіри',
        'character.creator.face.mix': 'Змішування обличчя',
        'character.creator.eyes': 'Очі',
        'character.creator.body.type': 'Тип тіла',
        'character.creator.save': 'Зберегти',
        'character.creator.processing': 'Обробка...',
        'character.creator.hair': 'Волосся',
        'character.creator.hair.color': 'Колір волосся',
        'character.creator.hair.highlight': 'Мелірування волосся',
        'character.creator.eyebrows': 'Брови',
        'character.creator.eyebrows.color': 'Колір брів',
        'character.creator.facial.hair': 'Волосся',
        'character.creator.facial.color': 'Колір волосся',
        'character.creator.category': 'Категорія',
        'character.creator.nose.width': 'Ширина носа',
        'character.creator.nose.height': 'Висота носа',
        'character.creator.nose.length': 'Довжина носа',
        'character.creator.nose.profile': 'Профіль носа',
        'character.creator.nose.tip': 'Кінчик носа',
        'character.creator.nose.broke': 'Зламаний ніс',
        'character.creator.brow.height': 'Висота брів',
        'character.creator.brow.depth': 'Глибина брів',
        'character.creator.cheek.height': 'Висота щік',
        'character.creator.cheek.depth': 'Глибина щік',
        'character.creator.cheek.puffed': 'Пухлісь щік',
        'character.creator.eyes.size': 'Розмір очей',
        'character.creator.lips.size': 'Розмір губ',
        'character.creator.jaw.width': 'Ширина щелепи',
        'character.creator.jaw.rounded': 'Округлість щелепи',
        'character.creator.chin.height': 'Висота підборіддя',
        'character.creator.chin.depth': 'Глибина підборіддя',
        'character.creator.chin.pointed': 'Гострота підборіддя',
        'character.creator.chin.dimple': 'Ямочки на підборідді',
        'character.creator.neck.size': 'Розмір шиї',
    },
    hu: {
        "character.creator.unable.to.save": "Nem sikerült menteni a karaktert, csatlakozz újra a szerverre",
        "character.creator.blemishes": "Hibák",
        "character.creator.visibility": "Láthatóság",
        "character.creator.sun.damage": "Nap károsítása",
        "character.creator.damage": "Kár",
        "character.creator.freckles": "Szeplők",
        "character.creator.aging": "Öregedés",
        "character.creator.lipstick": "Rúzs",
        "character.creator.color": "Szín",
        "character.creator.blusher": "Arcpirosító",
        "character.creator.makeup": "Smink",
        "character.creator.blemish": "Hiba",
        "character.creator.face.father": "Arc Apa",
        "character.creator.face.mother": "Arc Anya",
        "character.creator.skin.father": "Bőr Apa",
        "character.creator.skin.mother": "Bőr Anya",
        "character.creator.skin.mix": "Bőrkeverék",
        "character.creator.face.mix": "Arc keverék",
        "character.creator.eyes": "Szemek",
        "character.creator.body.type": "Testtípus",
        "character.creator.save": "Mentés",
        "character.creator.processing": "Feldolgozás...",
        "character.creator.hair": "Haj",
        "character.creator.hair.color": "Hajszín",
        "character.creator.hair.highlight": "Hajfény",
        "character.creator.eyebrows": "Szemöldök",
        "character.creator.eyebrows.color": "Szemöldökszín",
        "character.creator.facial.hair": "Arcszőrzet",
        "character.creator.facial.color": "Arcszőrzet színe",
        "character.creator.category": "Kategória",
        "character.creator.nose.width": "Orrszélesség",
        "character.creator.nose.height": "Orrmagasság",
        "character.creator.nose.length": "Orrhossz",
        "character.creator.nose.profile": "Orrprofil",
        "character.creator.nose.tip": "Orrhegy",
        "character.creator.nose.broke": "Összetört orr",
        "character.creator.brow.height": "Szemöldök magassága",
        "character.creator.brow.depth": "Szemöldök mélysége",
        "character.creator.cheek.height": "Pofa magassága",
        "character.creator.cheek.depth": "Pofa mélysége",
        "character.creator.cheek.puffed": "Puffadt pofa",
        "character.creator.eyes.size": "Szemek mérete",
        "character.creator.lips.size": "Ajak mérete",
        "character.creator.jaw.width": "Állkapocs szélessége",
        "character.creator.jaw.rounded": "Kerek állkapocs",
        "character.creator.chin.height": "Áll magassága",
        "character.creator.chin.depth": "Áll mélysége",
        "character.creator.chin.pointed": "Csúcsos áll",
        "character.creator.chin.dimple": "Gyűrűs áll",
        "character.creator.neck.size": "Nyak mérete"
    }    
});
