import { useTranslate } from '@Shared/translate.js';
const { setBulk } = useTranslate();

setBulk({
    en: {
        'character.creator.unable.to.save': 'Unable to save character, rejoin server',
        'character.creator.blemishes': 'Blemishes',
        'character.creator.visibility': 'Visibility',
        'character.creator.sun.damage': 'Sun Damage',
        'character.creator.damage': 'Damage',
        'character.creator.freckles': 'Freckles',
        'character.creator.aging': 'Aging',
        'character.creator.lipstick': 'Lipstick',
        'character.creator.color': 'Color',
        'character.creator.blusher': 'Blusher',
        'character.creator.makeup': 'Makeup',
        'character.creator.blemish': 'Blemish',
        'character.creator.face.father': 'Face Father',
        'character.creator.face.mother': 'Face Mother',
        'character.creator.skin.father': 'Skin Father',
        'character.creator.skin.mother': 'Skin Mother',
        'character.creator.skin.mix': 'Skin Mix',
        'character.creator.face.mix': 'Face Mix',
        'character.creator.eyes': 'Eyes',
        'character.creator.body.type': 'Body Type',
        'character.creator.save': 'Save',
        'character.creator.processing': 'Processing...',
        'character.creator.hair': 'Hair',
        'character.creator.hair.color': 'Hair Color',
        'character.creator.hair.highlight': 'Hair Highlight',
        'character.creator.eyebrows': 'Eyebrows',
        'character.creator.eyebrows.color': 'Eyebrows Color',
        'character.creator.facial.hair': 'Facial Hair',
        'character.creator.facial.color': 'Facial Hair Color',
        'character.creator.category': 'Category',
        'character.creator.nose.width': 'Nose Width',
        'character.creator.nose.height': 'Nose Height',
        'character.creator.nose.length': 'Nose Length',
        'character.creator.nose.profile': 'Nose Profile',
        'character.creator.nose.tip': 'Nose Tip',
        'character.creator.nose.broke': 'Nose Broke',
        'character.creator.brow.height': 'Brow Height',
        'character.creator.brow.depth': 'Brow Depth',
        'character.creator.cheek.height': 'Cheek Height',
        'character.creator.cheek.depth': 'Cheek Depth',
        'character.creator.cheek.puffed': 'Cheek Puffed',
        'character.creator.eyes.size': 'Eyes Size',
        'character.creator.lips.size': 'Lips Size',
        'character.creator.jaw.width': 'Jaw Width',
        'character.creator.jaw.rounded': 'Jaw Round',
        'character.creator.chin.height': 'Chin Height',
        'character.creator.chin.depth': 'Chin Depth',
        'character.creator.chin.pointed': 'Chin Pointed',
        'character.creator.chin.dimple': 'Chin Dimple',
        'character.creator.neck.size': 'Neck Size',
    },
});
